### PR TITLE
Add support for ONNX Runtime configuration

### PR DESCRIPTION
**Pull request by prinx**
## Description of changes

In #55, @nikhedonia made an update to make asset loading configurable. But that did not include ONNX web asset paths. The proposed solution of importing `ort` and making the configuration on it too does not work because the instance imported is different from the instance that will be used internally in the package.

This change exposes `ort` for its configuration:

```js
const recorder = await MicVAD.new({
    workletURL: '/build/vad.worklet.bundle.min.js',
    modelURL: '/build/silero_vad.onnx',

    // If present, this function will be called in the package to config ort
    ortConfig: (ort) => {
        ort.env.wasm.wasmPaths = "/build/"
    },
})
```

I also added a Dockerfile to run tests in a container, since I'm on Fedora and `playright` does not support non-Ubuntu environments. This may help other people who are not running on Ubuntu.
 
## List of changes

- add support for ONNX Runtime configuration
- add Dockerfile for testing in non-Ubuntu environments

## Checklist

- [ ] Added a test to verify that changes work as expected (if one doesn't exist already) 
- [ ] Ran automated tests successfully 
- [ ] Viewed manual test site and verified that pages are working 
- [x] Bumped versions in relevant packages
- [x] Updated relevant changelogs

### CODE REVIEW

**Comment by prinx** [comment]
Is there any specific configuration to run the tests? I would be grateful to have some guidance on that.

**Comment by ricky0123** [comment]
Thanks @prinx this looks good. As for running the tests you can see [here](https://wiki.vad.ricky0123.com/en/docs/developer/hacking). I'll try to look at this more closely and merge it later this week

**Comment by ricky0123** [comment]
Merged. Thanks @prinx !

**Comment by prinx** [comment]
Thank you so much @ricky0123 for the changes and for merging. And thank you for a great package.

**Pull request merged**
