### PR TITLE
Fire `onSpeechEnd` or `onVadMisfire` on pause

### LINKED ISSUE #30: Pause VAD during speech not triggering `onSpeechEnd` or `onVADMisfire`
Hi, @ricky0123 ! Thx for the useful project.

Currently, when `vad.pause()` is called during speech, neither `onSpeechEnd` nor `onVADMisfire` are triggered. As a result, the last speech section data is discarded. I believe that after `onSpeechStart` is called, either `onSpeechEnd` or `onVADMisfire` should always be triggered.

Expected Behavior:
If `vad.pause()` is called after `onSpeechStart` but before the end of the speech, there should be an implementation in place to trigger either `onSpeechEnd` or `onVADMisfire` at that point.

What do you think of this behavior? Please let me know if any further information or clarification is required!

### PR DESCRIPTION
**Pull request by HayatoYagi**
Fix #30 based on #45

Currently, the last speech segment can be discarded on pause. This PR fixes the behavior to treat a pause as something similar to stopping speaking.

### CODE REVIEW

**Comment by HayatoYagi** [comment]
I wanted to test this PR with my updated test site so the base branch is #62, but these two PRs have nothing to do with each other.

**Comment by ricky0123** [comment]
Hi @HayatoYagi , thanks for opening this PR. This would be a breaking change, though, and so I would not want to merge it as is. I would be open to enabling this behavior via the method I suggested [here](https://github.com/ricky0123/vad/issues/30#issuecomment-1605658371), or really any way that doesn't change the default behavior.

**Comment by ricky0123** [comment]
Hi @HayatoYagi

> The difference in timing when pressing the pause button for just one frame, which is uncontrollable for the users, after finishing a long speech leads to the inconsistency whether entire speech is discarded or not.

I don't quite understand what you mean here, can you explain?

In my view, the pause button is something the user presses to stop all functionality associated with the VAD, not to clip and submit the current audio.

In any case, it's a substantial change from the default behavior, so I don't want to do it. Possibly a better solution than an extra parameter to the onSpeechEnd callback is to add a new option at initialization. Eg
```ts
myvad = await MicVAD.new({ submitUserSpeechOnPause: true })
```
or something similar. I agree with you that each option we add increases the complexity for developers, but this is clearly an important issue about which people have different intuitions, so it's an important option to add. And I do not want to change the default behavior right now. If we had enough of a community on Discord, I would maybe leave it to a poll, but we have few enough people on Discord that I wouldn't trust the poll to be representative. So let's just implement the initialization option unless you have a different idea.

**Comment by HayatoYagi** [comment]
> I don't quite understand what you mean here, can you explain?

1a. The user finishes speaking.
2a. Press the pause button after redemptionFrames have elapsed.
3a. onSpeechEnd is triggered.

1b. The user finishes speaking.
2b. Press the pause button when `redemptionFrames-1` have elapsed.
3b. The entire last speech segment is discarded.

The difference between 2a and 2b is only a 1-frame timing distinction. While users shouldn't be conscious of the redemption frame, they are required to wait for the redemption frame to elapse before pressing the pause button.

**Comment by HayatoYagi** [comment]
@ricky0123 
I've added an option to enable this change.

> If we had enough of a community on Discord, I would maybe leave it to a poll

How many people do you think is enough?

**Comment by ricky0123** [comment]
Thanks for your PR @HayatoYagi I'll try to look at it tomorrow.

**Review by ricky0123 — APPROVED** [review]

**Comment by ricky0123** [comment]
Hi @HayatoYagi thanks for your contribution. I refactored it a little, added a couple of test pages, merged, and published it.

Thank you for clarifying what you meant about the redemption frames. I can see both perspectives. I guess it depends partially on why you think the user is pressing the pause button. For my use case, it was mostly something they would press if they were interrupted and wanted to discard the current speech segment (i.e. immediately stopping all functionality associated with the vad). I do agree that if you are using a long redemption period and they hit pause towards the end of it, it would produce an unexpected result from their perspective.

I haven't thought concretely about how many people I would want to participate in a poll. Hopefully, this PR will satisfy most people.

Thanks!

**Pull request merged**
