### PR TITLE
Add option for script processor node.

### PR DESCRIPTION
**Pull request by mkcode**
Hi Ricky - I'm sending this PR as an example of a potential major performance improvement, but it should not be merged as is.

The basic gist of this is that the current AudioWorklet implementation on mobile safari is broken to the point of being unusable. This actually means that WKWebView is broken and therefore all iPhone web browsers using AudioWorklet are unusable.

Lot's of people mentioning this here:
https://bugs.webkit.org/buglist.cgi?quicksearch=audio%20worklet

The code in this PR is a workaround. Yes, script processor node has been deprecated for a long time, but it still works and will likely continue working for a long time (at least until the webkit team fixes their AudioWorklet implementation)

This technique improves iOS performance 100x (subjectively).

I don't consider this mergable, and I was having a very tough time getting the demo site working locally with local changes. But it's enough to convey the workaround to you.

Perhaps the ideal is to do some sort of browser testing, and switch these methods out depending.

### CODE REVIEW

**Comment by ricky0123** [comment]
This is fantastic, thanks a ton. Unfortunately I pulled a muscle in my back
and am out of commission for a while, but I'm looking forward to taking a
closer look at this.

**Comment by ricky0123** [comment]
Hi Chris, it's a work in progress but I have an idea to make it a little better. I'll get back to you soon on it

**Comment by ricky0123** [comment]
Unfortunately, I spoke too soon. The truth is, I'm finding it hard to find any time for this project right now in my life. I'm happy to incorporate your changes though. And if you find a good workflow, you can share that too.

**Comment by kyb3r** [comment]
So did iOS fix their issue, because AudioWorkletNode is working fine on my mobile devices.

**Comment by ricky0123** [comment]
Decided that I'm not going to take this route, partially because Silero keeps updating and improving their models

**Comment by mkcode** [comment]
Hi All - just wanted to point out that the AudioWorklet issues with Safari have nothing to do with the CPU load, so improvements to Silero will not fix this particular issue. The issue exists in very simple setups like this: https://bugs.webkit.org/show_bug.cgi?id=226240

But I am not sure if the issue has been fixed. It may only come up in certain specific contexts as well. YMMV.

**Pull request closed without merging**
