### PR TITLE
Stream frames from resampler to non-real-time-vad

### LINKED ISSUE #94: NonRealTimeVAD hanging on large wav file
I'm trying to figure out why the NonRealTimeVAD seems to hang for my wav files in a node.js environment.

This is my code:

```
import fs from 'fs'
import { NonRealTimeVAD } from '@ricky0123/vad-node'
import wav from 'wav-decoder'

// Convert MP4 file to wav first:
// ffmpeg -i /Users/lachlan/Downloads/sian-initial.m4a -ar 16000 /Users/lachlan/Downloads/sian-initial.wav

function loadAudio(audioPath) {
  let buffer = fs.readFileSync(audioPath)
  let result = wav.decode.sync(buffer)
  let audioData = new Float32Array(result.channelData[0].length)
  for (let i = 0; i < audioData.length; i++) {
    for (let j = 0; j < result.channelData.length; j++) {
      audioData[i] += result.channelData[j][i]
    }
  }
  return [audioData, result.sampleRate]
}

const myvad = await NonRealTimeVAD.new(/** @type {import('@ricky0123/vad-node').NonRealTimeVADOptions} */ ({ }))

const [audioData, sampleRate] = loadAudio('/Users/lachlan/Downloads/sian-initial.wav')

console.log(`Audio data size: ${audioData.length} Sample rate: ${sampleRate}`)

for await (const { audio, start, end } of myvad.run(audioData, sampleRate)) {
  console.log(`Speech segment: ${start}, ${end}`)
}
```

I get this output (I removed the warnings that are related to CleanUnusedInitializersAndNodeArgs):

```
❯ node scripts/splitAudio.js
[VAD] initializing vad
[VAD] vad is initialized
Audio data size: 45794645 Sample rate: 16000
```

At this point it hangs. 

When run with the example wav at https://github.com/ricky0123/vad/blob/ea584aaf66d9162fb19d9bfba607e264452980c3/examples/node/test.wav it works fine:

```    
[VAD] vad is initialized
Audio data size: 225992 Sample rate: 44100
Speech segment: 2112, 4416
```

Interesting that the test file is a sample rate of 44100. I tried converting my wav file to that sample rate, but got an error:

```
[VAD] vad is initialized
Audio data size: 126221492 Sample rate: 44100

#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804 (see crbug.com/1201626)
```

### PR DESCRIPTION
**Pull request by lox**
## Description of changes

Previously large files would take a long time to resample, this streams resampled frames to the FrameProcessor as they are ready. 

It also tweaks the example for node to optionally allow a file to be passed as an argument for easy testing.

Fixes #94 

## Checklist

- [ ] Added a test to verify that changes work as expected (if one doesn't exist already) 
- [ ] Ran automated tests successfully 
- [ ] Viewed manual test site and verified that pages are working 
- [ ] Bumped versions in relevant packages
- [ ] Updated relevant changelogs

### CODE REVIEW

**Comment by ricky0123** [comment]
Thanks @lox. I'll take a look at this later this week

**Comment by ricky0123** [comment]
Hi @lox the tests are not passing. Can you run `npm run build && npm run test`?

**Comment by lox** [comment]
Will do! Haven't got to tests yet, will shortly and mark the PR as final.

**Comment by ricky0123** [comment]
Thanks!

**Pull request closed without merging**
