### PR TITLE
add prompt indicating that the model or worklet cannot be found

### PR DESCRIPTION
**Pull request by zhaonx**
## Description of changes
I am a Vue user, and while using VAD (Voice Activity Detection) in different projects, I noticed that the locations of .wasm and .onnx files often need to be adjusted as the project evolves. However, it's easy to forget where these files should be placed under the current router after some time. Many issues also mention 'The user aborted a request,' which I find not very user-friendly, especially for new or infrequent users.

Therefore, I made some modifications to the program to provide a more informative error message, helping users understand the real cause of the error and facilitating a quick start for both new and existing users of VAD.
image

## Checklist

- [ ] Added a test to verify that changes work as expected (if one doesn't exist already) 
- [ ] Ran automated tests successfully 
- [ ] Viewed manual test site and verified that pages are working 
- [ ] Bumped versions in relevant packages
- [ ] Updated relevant changelogs

### CODE REVIEW

**Comment by ricky0123** [comment]
Hi @zhaonx thanks for your contribution, this is a nice addition! How about using this message instead?
```
        `Encountered an error while loading audio worklet. Please make sure the worklet is available at the specified path:
        ${fullOptions.workletURL} 
      If need be, you can customize the worklet file location using the \`workletURL\` option.`
```
This way we are showing the true path where we are looking for the audio worklet, which the user may have customized. I think the message related to onnx file location would be better off in a different error message.

**Comment by zhaonx** [comment]
Sorry for the slow reply.
I'm using vite+vue, and the project will use router to configure routing information. The reason why I use `const currentPath = window.location.pathname; `It's because the root directory of the web page will change.
For example,the router in my project is
 `
{
    path: '/enterpriseLevelScreen',
    component: EnterPrisekIndex,
    redirect: '/enterpriseLevelScreen/allProject'}
` 
and it occured
`Cannot find files in this path /enterpriseLevelScreen. 
            You can add your model related files 
            (ort-wasm.wasm, ort-wasm-simd.wasm, ort-wasm-threaded.wasm, silero vad.onnx, vad.worklet.bundle.min.js) 
            to this path.`
In this case, I need to put the file inside this for it to run successfully
image

Providing only the fullOptions.worklet URL will still make the user not know where the root directory of the worklet is on the web page, and it will still not work if you put it in a random location.
How about using this message instead?
``Encountered an error while loading audio worklet. Please make sure the worklet is available at the specified path:
        ${fullOptions.workletURL} ,current root path is ${currentPath},
      If need be, you can customize the worklet file location using the \`workletURL\` option.``

**Comment by ricky0123** [comment]
Hi @zhaonx thanks a lot for your patience. So, I don't have any experience wth Vue, but I think I see the problem here. Let's say in the web root you have `subdir/index.html` and `subdir/index.js` where the Javascript file loads the vad but does not specify `workletURL` or `modelURL`. Then by default we are going to load
https://github.com/ricky0123/vad/blob/06e7724b84a5099965224e99610ec621d81b15e7/packages/web/src/real-time-vad.ts#L81
https://github.com/ricky0123/vad/blob/06e7724b84a5099965224e99610ec621d81b15e7/packages/web/src/asset-path.ts#L8-L18
which resolves just to `vad.worklet.bundle.min.js`, which is a relative path. So my suggestion of just telling the user to put the worklet it `${fullOptions.workletURL}` is a bit useless as it will just say `vad.worklet.bundle.min.js`. What we would want to tell the user in this case is that they should put it in `/subdir/vad.worklet.bundle.min.js`, which is more specific.

I think what I would like to do is change this line
https://github.com/ricky0123/vad/blob/06e7724b84a5099965224e99610ec621d81b15e7/packages/web/src/asset-path.ts#L8
to 
```javascript
let basePath = "/"
```
and change the error message to
```
        `Encountered an error while loading audio worklet. Please make sure the worklet vad.bundle.min.js included with @ricky0123/vad-web is available at the specified path:
        ${fullOptions.workletURL} 
Please make sure the model silero_vad.onnx included with @ricky0123/vad-web is available at the specified path:
        ${fullOptions.modelURL} 
If need be, you can customize the worklet file location using the \`workletURL\` option.``
```
Then `${fullOptions.workletURL}` and `${fullOptions.modelURL}` will show the full paths where the files are supposed to be.

I would rather leave the path for the wasm files out of this PR because those are configured in a different way, and there is currently a different PR related to that. I will try to add that to the error message in the future.

**Comment by ricky0123** [comment]
Merged. Thanks @zhaonx !

**Pull request merged**
